services:
  bot:
    build: .
    container_name: nofuss
    restart: unless-stopped
    env_file: .env
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "${HTTP_PORT:-8080}:8080"
    volumes:
      - ./data:/app/data